Update workflow

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -79,6 +79,7 @@ jobs:
               with:
                   cmd: run encore dev
 
+            # https://github.com/marketplace/actions/setup-chromedriver
             - name: Start chromedriver
               uses: nanasess/setup-chromedriver@master
               with:
@@ -90,20 +91,36 @@ jobs:
                 chromedriver --url-base=/wd/hub &
                 sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
 
-            - name: Start mysql service
-              run: sudo /etc/init.d/mysql start
+            - name: Set up JDK 1.8
+              uses: actions/setup-java@v1
+              with:
+                java-version: 1.8
 
-            - name: Install database
-              run: |
-                  symfony console doctrine:database:create || echo "Error while creating the DB"
-              env:
-                DATABASE_URL: mysql://root:chamilo@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/chamilo
-                DATABASE_HOST: 127.0.0.1
-                DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
-                DATABASE_NAME: chamilo
-                DATABASE_USER: root
-                DATABASE_PASSWORD: chamilo
-                APP_INSTALLED: 1
+            - name: Selenium
+            - run: |
+                wget http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
+                java -jar selenium-server-standalone-3.141.59.jar -log selenium.log  > /dev/null &
+
+#            - name: Start mysql service
+#              run: sudo /etc/init.d/mysql start
+#
+#            - name: Install database
+#              run: |
+#                  symfony console doctrine:database:create || echo "Error while creating the DB"
+#              env:
+#                DATABASE_URL: mysql://root:chamilo@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/chamilo
+#                DATABASE_HOST: 127.0.0.1
+#                DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
+#                DATABASE_NAME: chamilo
+#                DATABASE_USER: root
+#                DATABASE_PASSWORD: chamilo
+#                APP_INSTALLED: 1
+
+            - name: Apache
+            - run: |
+                  sudo apt install apache2
+                  sudo a2enmod rewrite actions alias
+                  sudo service apache2 restart
 
             - name: Composer analyse
               run: composer analyse
