Update gh actions

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -35,18 +35,36 @@ jobs:
                   tools: behat
                   extensions: mbstring, xml, ctype, iconv, mysql, gd, soap, intl, zip, bcmath
 
-            -  name: Start mysql service
-               run: sudo /etc/init.d/mysql start
+            - name: Start mysql service
+              run: sudo /etc/init.d/mysql start
+
+            - name: Get composer cache directory
+              id: composer-cache
+              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+
+            - name: Cache composer dependencies
+              uses: actions/cache@v2
+              with:
+                path: ${{ steps.composer-cache.outputs.dir }}
+                # Use composer.json for key, if composer.lock is not committed.
+                # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
+                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
+                restore-keys: ${{ runner.os }}-composer-
 
             - name: Install dependencies
               run: composer install --prefer-dist --no-progress --no-suggest --no-scripts
 
-            - name: Run Migration
+            - name: Install database
               run: |
-                  php bin/console doctrine:database:create || echo "Create schema"
+                  php bin/console doctrine:database:create || echo "Error while creating the DB"
 
               env:
-                DATABASE_URL: mysql://root:chamilo@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/chamilo
+                #DATABASE_URL: mysql://root:chamilo@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/chamilo
+                DATABASE_HOST: 127.0.0.1
+                DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
+                DATABASE_NAME: root
+                DATABASE_USER: chamilo
+                DATABASE_PASSWORD: chamilo
                 APP_INSTALLED: 1
 
             - name: Composer analyse
